### ISSUE TITLE
Selecting one category makes multiple selections.

### ISSUE THREAD

**Issue by amendoxa** [liprec/powerbi-hierarchySlicer#33]
I am not sure how to describe the issue but I'll start by explaining the behavior after multiple attempts to understand this.

I have created a file with 2 very basic hierarchies which are in essence exactly the same. On the first one I have 'IT" and 'Non-IT' as the first layer of the Hierarchy and the Second one I have 'Cat1' and 'Cat2'. While the second one works perfectly, the first one selects both (IT and Non IT) when I only click on 'IT'. I believe this issue to be caused by the fact that the word 'IT' is contained in both as the second slicer does not have that problem. Hope the attached file help you understand the issue a bit further.

Thank you for the support.

![hierarchyslicerissue](https://user-images.githubusercontent.com/37668794/42652217-f30935bc-85ce-11e8-9263-e138bbf9f0b5.PNG)

**Comment by liprec** [comment]
Can you share a sample PBIX file with me? I don't see the attachment.

**Comment by amendoxa** [comment]
[HierarchySlicerIssueDemo.zip](https://github.com/liprec/powerbi-hierarchySlicer/files/2193578/HierarchySlicerIssueDemo.zip)

Thank you for your help, is there anyway I can get V 1.1.5 to roll back my reports?

**Comment by shreyanshmohnot** [comment]
Hey @amendoxa I had the same issue because most of my fields in hierarchy levels were null(<blank>) and when you switch off the Empty Leaf feature, the slicer does not select everything.
However, when feature is enabled everything is selected. Maybe try looking into some fields in your dataset, they might contain null(<blank>) and that whose be causing problem. If you try to replace those null(<blank>) values with some dummy values, it might work as per required. In may case it worked that way so. If not then, ignore this.
Thanks

**Comment by amendoxa** [comment]
Thank you @shreyanshmohnot Initially that was my thought as well reason why I created that condensed hierarchy for testing, and it did not perform differently. It did work though when I added an extra space at the end of IT ("IT_"). Thank you for sharing though.

**Comment by liprec** [comment]
Fixed with version v1.3
