### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by jayantpatodi** [liprec/powerbi-hierarchySlicer#44]
Hi,

The search bar is not working when you enable the select all option from the 'selection' option for the visual. 
For eg:
I have just created a random dataset with Column 1 being alphabets and column 2 being numbers and am trying to search a particular value in the slicer. But the search bar wont work if I have enable the select all function. It's working fine when the select all function is disabled. 

Can you please fix this asap ?

[HierarchySlicer_SearchBarBug.pptx](https://github.com/liprec/powerbi-hierarchySlicer/files/2434004/HierarchySlicer_SearchBarBug.pptx)

**Comment by liprec** [comment]
There is an issue with the combination of the search option and the 'Select All' option.will be 
This will be fixed in a next version. At this moment I do not have an ETA yet.

**Comment by MarceMarti** [comment]
Hi Jan,

I wonder if this issue is related to the glitch in  adding the search button but then unable to disable it by clicking on search back again? it appears that when I select search the bar stays stuck unless I do a full refresh - F5. This behaviour is not present with the custom slicer power BI has. I can either pop it or conceale it w/o issues.

Thanks for what you've done, it's outstanding how much value this custom visual provides to our company.

**Comment by Darryl284** [comment]
Any updates as to when this fix will be available?

**Comment by liprec** [comment]
The v2 version is now available and should fix this issue.

Thanks, Jan Pieter

**Comment by tony189** [comment]
Hi!!!
First, just want to thank you this awesome visual, great work.

I've been trying to use the slicer with the select all option and the search bar, and I couldn't make it work. 

I've been reading through the versions info, and the comments and it seems you already fixed it, so I'm wondering wether I'm doing something wrong. 

could you help me with this issue?

Thanks again!

**Comment by PowerBIEdu** [comment]
Hello,
first, just want to thank you for this awesome visual.

I couldn't make it work either.

Could you help us?

Kind regards
