### ISSUE TITLE
[v2-branch] Selection disappears

### ISSUE THREAD

**Issue by uve** [liprec/powerbi-hierarchySlicer#71]
The bug I could spot is the initial selection when you first interact with the visual  ( the check-mark) is shortly visible – it then disappears and shows up again once the 
Filter is applied to the model. 
I am not able to reproduce it with a small hierarchy so it could maybe related to our complex and large hierarchy. 
But the issue is: 
Multi-Select enabled -> select an Element –> section is shortly visible -> disappears while the model is filtered -> once the data is filtered the selection is visible in the Visual again.

Once you have interacted with the visual, this behavior is not showing again. ( Only on first interaction I assume)

**Comment by liprec** [comment]
Hi @uve,
I got the feeling that this is due to the fact that the `jsonFilter` Power BI returns is inconsistent in the order of the filter columns and therefor the visual is not able to extract the current selection anymore.
BTW: does it only happen if you have multiple levels and select not the first level?
