### ISSUE TITLE
error on deselecting leaf

### ISSUE THREAD

**Issue by IlarioAncora** [liprec/powerbi-hierarchySlicer#78]
I get an error when deselecting a leaf, if root is selected. It simply doesn't work, it endlessly try to load the data. Is there a fix? 
Thank you
---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=e7e0e95e-f3f0-4112-9a46-fde2a59d2d51
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html

**Comment by toastoftown** [comment]
Hi Jan,

Issue with select and deselect from root.

For our hierarchy implementation [org] we have levels up to 5. 

2 Names under level 2 (A&B)
1 Name under Level 5 (C) C is under A's hierarchy & B doesn't have any level 5 users

In our scenario the last level i.e. level 5 doesn't have any data in the table and all other levels have data. When I go to level 2 directly the chart plots are as expected. If we go to level 5 the chart comes up as empty since he has no data (as expected). But if'm traversing from root and uncheck the level 2[i.e B who has no level 5 user], so A remains checked in the hierarchy slicer [level 2 user] but the chart here comes up as empty which shouldn't happen because level 2 has data. I guess, since the entire chain is being selected, the data [zero values] from level 5 overrides the level 2.

Ideally if I'm traversing from root and deselect at any level/leaf, the value should be picked for that corresponding level instead of pulling the data for entire chain. 

Please share your inputs.

**Comment by liprec** [comment]
As a new version is released last month and that contains a different selection logic I will close this issue. 
It this is still an issue, please let me know.

Thanks, Jan Pieter
